class NotesWorker
  include Sidekiq::Worker

  def perform(support_request_id)
    support_request = SupportRequest.find_by(id: support_request_id)
    return unless support_request
    note_text = "Support request generated by #{support_request.user.name}"
    support_request.notes.create!(text: note_text, notable_action: "create")
  end
end